// Mocks generated by Mockito 5.4.6 from annotations
// in one_coffee/test/helpers/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:one_coffee/features/brew_logger/domain/entities/brew_record.dart'
    as _i4;
import 'package:one_coffee/features/brew_logger/domain/repositories/brew_repository.dart'
    as _i2;
import 'package:one_coffee/features/history/domain/entities/brew_summary.dart'
    as _i11;
import 'package:one_coffee/features/history/domain/repositories/history_repository.dart'
    as _i10;
import 'package:one_coffee/features/inventory/domain/entities/bean.dart' as _i6;
import 'package:one_coffee/features/inventory/domain/entities/equipment.dart'
    as _i7;
import 'package:one_coffee/features/inventory/domain/repositories/inventory_repository.dart'
    as _i5;
import 'package:one_coffee/features/rating/domain/entities/brew_rating.dart'
    as _i9;
import 'package:one_coffee/features/rating/domain/repositories/rating_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BrewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrewRepository extends _i1.Mock implements _i2.BrewRepository {
  MockBrewRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.BrewRecord>> getAllBrewRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBrewRecords, []),
            returnValue: _i3.Future<List<_i4.BrewRecord>>.value(
              <_i4.BrewRecord>[],
            ),
          )
          as _i3.Future<List<_i4.BrewRecord>>);

  @override
  _i3.Stream<List<_i4.BrewRecord>> watchAllBrewRecords() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllBrewRecords, []),
            returnValue: _i3.Stream<List<_i4.BrewRecord>>.empty(),
          )
          as _i3.Stream<List<_i4.BrewRecord>>);

  @override
  _i3.Future<_i4.BrewRecord?> getBrewRecordById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBrewRecordById, [id]),
            returnValue: _i3.Future<_i4.BrewRecord?>.value(),
          )
          as _i3.Future<_i4.BrewRecord?>);

  @override
  _i3.Future<int> createBrewRecord(_i4.BrewRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#createBrewRecord, [record]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateBrewRecord(_i4.BrewRecord? record) =>
      (super.noSuchMethod(
            Invocation.method(#updateBrewRecord, [record]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteBrewRecord(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBrewRecord, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}

/// A class which mocks [InventoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepository extends _i1.Mock
    implements _i5.InventoryRepository {
  MockInventoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.Bean>> getAllBeans() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBeans, []),
            returnValue: _i3.Future<List<_i6.Bean>>.value(<_i6.Bean>[]),
          )
          as _i3.Future<List<_i6.Bean>>);

  @override
  _i3.Future<List<_i6.Bean>> searchBeans(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchBeans, [query]),
            returnValue: _i3.Future<List<_i6.Bean>>.value(<_i6.Bean>[]),
          )
          as _i3.Future<List<_i6.Bean>>);

  @override
  _i3.Future<int> createBean(_i6.Bean? bean) =>
      (super.noSuchMethod(
            Invocation.method(#createBean, [bean]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateBean(_i6.Bean? bean) =>
      (super.noSuchMethod(
            Invocation.method(#updateBean, [bean]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteBean(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBean, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> incrementBeanUseCount(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#incrementBeanUseCount, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.Equipment>> getAllEquipments() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEquipments, []),
            returnValue: _i3.Future<List<_i7.Equipment>>.value(
              <_i7.Equipment>[],
            ),
          )
          as _i3.Future<List<_i7.Equipment>>);

  @override
  _i3.Future<List<_i7.Equipment>> searchEquipments(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchEquipments, [query]),
            returnValue: _i3.Future<List<_i7.Equipment>>.value(
              <_i7.Equipment>[],
            ),
          )
          as _i3.Future<List<_i7.Equipment>>);

  @override
  _i3.Future<int> createEquipment(_i7.Equipment? equipment) =>
      (super.noSuchMethod(
            Invocation.method(#createEquipment, [equipment]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateEquipment(_i7.Equipment? equipment) =>
      (super.noSuchMethod(
            Invocation.method(#updateEquipment, [equipment]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteEquipment(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEquipment, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> incrementEquipmentUseCount(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#incrementEquipmentUseCount, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [RatingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRatingRepository extends _i1.Mock implements _i8.RatingRepository {
  MockRatingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i9.BrewRating?> getRatingForBrew(int? brewRecordId) =>
      (super.noSuchMethod(
            Invocation.method(#getRatingForBrew, [brewRecordId]),
            returnValue: _i3.Future<_i9.BrewRating?>.value(),
          )
          as _i3.Future<_i9.BrewRating?>);

  @override
  _i3.Future<int> createRating(_i9.BrewRating? rating) =>
      (super.noSuchMethod(
            Invocation.method(#createRating, [rating]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> updateRating(_i9.BrewRating? rating) =>
      (super.noSuchMethod(
            Invocation.method(#updateRating, [rating]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteRating(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRating, [id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}

/// A class which mocks [HistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRepository extends _i1.Mock implements _i10.HistoryRepository {
  MockHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i11.BrewSummary>> getAllBrewSummaries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBrewSummaries, []),
            returnValue: _i3.Future<List<_i11.BrewSummary>>.value(
              <_i11.BrewSummary>[],
            ),
          )
          as _i3.Future<List<_i11.BrewSummary>>);

  @override
  _i3.Future<List<_i11.BrewSummary>> filterBrewSummaries(
    _i10.BrewFilter? filter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filterBrewSummaries, [filter]),
            returnValue: _i3.Future<List<_i11.BrewSummary>>.value(
              <_i11.BrewSummary>[],
            ),
          )
          as _i3.Future<List<_i11.BrewSummary>>);

  @override
  _i3.Future<List<_i11.BrewSummary>> getTopBrews({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getTopBrews, [], {#limit: limit}),
            returnValue: _i3.Future<List<_i11.BrewSummary>>.value(
              <_i11.BrewSummary>[],
            ),
          )
          as _i3.Future<List<_i11.BrewSummary>>);
}
